import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { v4 as uuidv4 } from 'uuid';
import { getApiKey, saveRecipe } from '../services/storage';
import { generateRecipe } from '../services/openai';
import { parseRecipeText } from '../services/parser';

export default function GenerateRecipe() {
  const navigate = useNavigate();
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    if (!getApiKey()) {
      setError('Please set your OpenAI API key in Settings first.');
      return;
    }

    setLoading(true);
    setError('');
    setResult('');
    setSaved(false);

    try {
      const text = await generateRecipe(prompt);
      setResult(text);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = () => {
    const parsed = parseRecipeText(result);
    const recipe = {
      id: uuidv4(),
      title: parsed.title || 'AI Generated Recipe',
      ingredients: parsed.ingredients,
      instructions: parsed.instructions,
      prepTime: parsed.prepTime,
      servings: 4,
      cuisines: parsed.cuisines,
      types: parsed.types,
      utensils: parsed.utensils,
      photoUrl: '',
      rating: 0,
      notes: 'Generated by AI',
      versions: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    saveRecipe(recipe);
    setSaved(true);
    setTimeout(() => navigate(`/recipe/${recipe.id}`), 600);
  };

  return (
    <div>
      <h1>AI Recipe Generator</h1>
      <p className="text-muted mb-2">
        Describe what you want to cook. The AI will use your ingredient preferences and cooking style.
      </p>

      {error && <div className="error-msg">{error}</div>}
      {saved && <div className="success-msg">Recipe saved to your library!</div>}

      <div className="generate-form">
        <div className="form-group">
          <label>What would you like to cook?</label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder={'Examples:\n- A healthy Indian dinner for 4 using lentils\n- Something quick with paneer and spinach\n- A vegetarian Thanksgiving main dish\n- Remix my chicken curry but make it lighter'}
            style={{ minHeight: '100px' }}
          />
        </div>

        <button className="btn btn-primary" onClick={handleGenerate} disabled={loading}>
          {loading ? 'Generating...' : 'Generate Recipe'}
        </button>
      </div>

      {loading && (
        <div className="loading">
          <p>Creating your recipe...</p>
        </div>
      )}

      {result && (
        <div>
          <div className="ai-result">{result}</div>
          <div className="btn-group mt-2">
            <button className="btn btn-primary" onClick={handleSave}>Save to Library</button>
            <button className="btn btn-secondary" onClick={handleGenerate}>Regenerate</button>
          </div>
        </div>
      )}
    </div>
  );
}
